// <auto-generated />
using System;
using Custom5v5.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Custom5v5.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260318200726_MakeRankTierNullable")]
    partial class MakeRankTierNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Custom5v5.Infrastructure.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("LP")
                        .HasColumnType("integer")
                        .HasColumnName("lp");

                    b.Property<string>("PUUID")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puuid");

                    b.Property<int?>("PeakDivision")
                        .HasColumnType("integer")
                        .HasColumnName("peak_division");

                    b.Property<int>("PeakLp")
                        .HasColumnType("integer")
                        .HasColumnName("peak_lp");

                    b.Property<string>("PeakSeason")
                        .HasColumnType("text")
                        .HasColumnName("peak_season");

                    b.Property<string>("PeakTier")
                        .HasColumnType("text")
                        .HasColumnName("peak_tier");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prenom");

                    b.Property<int?>("RankDivision")
                        .HasColumnType("integer")
                        .HasColumnName("rank_division");

                    b.Property<string>("RankTier")
                        .HasColumnType("text")
                        .HasColumnName("rank_tier");

                    b.Property<string>("RiotId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("riot_id");

                    b.Property<int?>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_players_user_id");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Custom5v5.Infrastructure.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<long>("DiscordId")
                        .HasColumnType("bigint")
                        .HasColumnName("discord_id");

                    b.Property<string>("DiscordUsername")
                        .HasColumnType("text")
                        .HasColumnName("discord_username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Custom5v5.Infrastructure.Entities.Player", b =>
                {
                    b.HasOne("Custom5v5.Infrastructure.Entities.User", "User")
                        .WithOne("Player")
                        .HasForeignKey("Custom5v5.Infrastructure.Entities.Player", "UserId")
                        .HasConstraintName("fk_players_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Custom5v5.Infrastructure.Entities.User", b =>
                {
                    b.Navigation("Player");
                });
#pragma warning restore 612, 618
        }
    }
}
